name: Ejecutor ThingSpeak 10min

on:
  schedule:
    # Esto define la frecuencia (Cron). 
    # '*/10 * * * *' significa cada 10 minutos.
    - cron: '*/10 * * * *'
  workflow_dispatch: # Esto permite que lo ejecutes manualmente para probar

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script de Python
        env:
          # Aquí pasamos la API KEY de forma segura
          THINGSPEAK_KEY: ${{ secrets.THINGSPEAK_KEY }}
        run: python mi_script.py
